name = "encrypt"
type = "javascript"

kv_namespaces = [ 
  { binding = "kv", id = "CLOUDFLARE_KV_ID", preview_id = "CLOUDFLARE_KV_ID" }
]

account_id = "CLOUDFLARE_ACCOUNT_ID" 

workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-17"

[build.upload]
format = "modules"
dir = "./src"
main = "./index.js" # becomes "./src/worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]